{
 "title": "Cluster Capacity",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kubelet_running_pods, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Cores Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kubernetes_io:anthos_container_cpu_request_cores{cluster_name=\"$cluster\"}) / sum (kubernetes_io:anthos_node_cpu_allocatable_cores{cluster_name=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "1- sum(rate(kubernetes_io:anthos_node_cpu_core_usage_time{cluster_name=\"$cluster\"}[5m])) / sum(kubernetes_io:anthos_node_cpu_total_cores{cluster_name=\"$cluster\"})",
     "legendFormat": "% Idle"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "timeseries",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kubernetes_io:anthos_node_cpu_allocatable_cores{cluster_name=\"$cluster\"})",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "sum (kubernetes_io:anthos_container_cpu_request_cores{cluster_name=\"$cluster\"})",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_load1{cluster=\"$cluster\"})",
     "legendFormat": "load 1m"
    },
    {
     "expr": "sum(node_load5{cluster=\"$cluster\"})",
     "legendFormat": "load 5m"
    },
    {
     "expr": "sum(node_load15{cluster=\"$cluster\"})",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kubernetes_io:anthos_container_memory_request_bytes{cluster_name=\"$cluster\"}) / sum (kubernetes_io:anthos_node_memory_allocatable_bytes{cluster_name=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"}) - sum(node_memory_MemFree_bytes{cluster=\"$cluster\"}) - sum(node_memory_Buffers_bytes{cluster=\"$cluster\"}) - sum(node_memory_Cached_bytes{cluster=\"$cluster\"})) / sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"}))",
     "legendFormat": "% Free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (kubernetes_io:anthos_node_memory_allocatable_bytes{cluster_name=\"$cluster\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum (kubernetes_io:anthos_container_memory_request_bytes{cluster_name=\"$cluster\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"}) - sum(node_memory_MemFree_bytes{cluster=\"$cluster\"}) - sum(node_memory_Buffers_bytes{cluster=\"$cluster\"}) - sum(node_memory_Cached_bytes{cluster=\"$cluster\"})",
     "legendFormat": "memory usage"
    },
    {
     "expr": "sum(node_memory_Buffers_bytes{cluster=\"$cluster\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{cluster=\"$cluster\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{cluster=\"$cluster\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{cluster=\"$cluster\",device!=\"rootfs\"}) - sum(node_filesystem_free_bytes{cluster=\"$cluster\",device!=\"rootfs\"})) / sum(node_filesystem_size_bytes{cluster=\"$cluster\",device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity{cluster=\"$cluster\",resource=\"pods\"}) - sum(kube_pod_info{cluster=\"$cluster\"})) / sum(kube_node_status_capacity{cluster=\"$cluster\",resource=\"pods\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=\"$cluster\"})",
     "legendFormat": "Current number of Pods"
    },
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\",resource=\"pods\"})",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{cluster=\"$cluster\",device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{cluster=\"$cluster\",device!~\"lo\"}[5m]))"
    }
   ]
  }
 ]
}